from .local import Local

__version__ = "0.1"


local = Local()

GLOBAL_REQUEST_ID_HEADER = 'NSFOCUS-GLOBAL-REQUEST-ID'
PARENT_REQUEST_ID_HEADER = 'NSFOCUS-PARENT-REQUEST-ID'
REQUEST_ID_NUMBER_HEADER = 'NSFOCUS-REQUEST-ID-NUMBER'
